version: "2.4"

services:
  app:
    build:
      dockerfile: ./conf/app.Dockerfile
    volumes:
      - ./conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ./src:/var/www/html
    container_name: app

  web:
    image: nginx:1.25-alpine
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - "8080:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src:/var/www/html
    restart: always
    container_name: web
