apiVersion: serving.knative.dev/v1
kind: Service
metadata: 
  name: my-svc
  annotations: 
    run.googleapis.com/launch-stage: BETA
spec: 
  template: 
    metadata: 
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/execution-environment: gen1
        run.googleapis.com/container-dependencies: '{"web":["app"]}'
    spec: 
      containerConcurrency: 1
      containers:
      - name: app
        image: asia-northeast1-docker.pkg.dev/PROJECT_ID/my-apps/app:COMMIT_SHA
        env:
        - name: GIT_HASH
          value: COMMIT_SHA
        resources: 
          limits: 
            cpu: "0.1"
            memory: 128Mi
      - name: web
        image: asia-northeast1-docker.pkg.dev/PROJECT_ID/my-apps/web:COMMIT_SHA
        ports: 
        - containerPort: 80
        resources: 
          limits: 
            cpu: "0.1"
            memory: 128Mi
